//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internetShopProject.mainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_Id { get; set; }
        public string product_Name { get; set; }
        public Nullable<int> product_Count { get; set; }
        public string product_Description { get; set; }
        public Nullable<int> product_Price { get; set; }
    }
}
