//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internetShopProject.mainEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_Id { get; set; }
        public int role_Id { get; set; }
        public string user_Nickname { get; set; }
        public string user_Password { get; set; }
        public byte[] user_Image { get; set; }
    
        public virtual role role { get; set; }
    }
}
